version: "3"

services:
  # Dremio
  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    ports:
      - 9048:9047
      - 31010:31010
      - 32010:32010
      - 45678:45678
    container_name: dremio
    networks:
      dremio-mysql-superset: # MySQL
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: deptraiqua
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=exampledb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3307:3306"
    networks:
      dremio-mysql-superset:
        # Superset

networks:
  dremio-mysql-superset:
